server:
  port: 8585
  servlet:
    context-path: /api

spring:
  application:
    name: eazybytes
  devtools:
    add-properties: true # habilitado
  datasource:
    url: jdbc:mysql://localhost:3306/eazybytes?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: update
  security:
    user:
      name: eazybytes
      password: 123456


# Logs
logging:
  level:
    web: DEBUG
  file:
    name: application.log