server:
  port: 8585

spring:
  application:
    name: eazybytes
  devtools:
    add-properties: true
  datasource:
    url: jdbc:mysql://localhost:3306/eazybank?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/eazybankdev/protocol/openid-connect/certs

logging:
  level:
    web: DEBUG